// Code generated by protoc-gen-mqc. DO NOT EDIT.
// versions:
// protoc-gen-go-mqc v1.0.0

package test

import (
	"context"
	"fmt"
	"github.com/srand/mqc"
)

type RpcTestClient interface {
	Rpc(ctx context.Context, req *TestRequest) (*TestReply, error)
}

type RpcTestServer interface {
	Rpc(req *TestRequest) (*TestReply, error)
}

type ServerStreamTestClient interface {
	Stream(ctx context.Context, req *TestRequest) (mqc.ServerStreamClient[TestReply], error)
}

type ServerStreamTestServer interface {
	Stream(req *TestRequest, stream mqc.ServerStreamServer[TestReply]) error
}

type ClientStreamTestClient interface {
	Stream(ctx context.Context) (mqc.ClientStreamClient[TestRequest, TestReply], error)
}

type ClientStreamTestServer interface {
	Stream(stream mqc.ClientStreamServer[TestRequest, TestReply]) error
}

type BidiStreamTestClient interface {
	Stream(ctx context.Context) (mqc.BidiStreamClient[TestRequest, TestReply], error)
}

type BidiStreamTestServer interface {
	Stream(stream mqc.BidiStreamServer[TestRequest, TestReply]) error
}

type rpcTestClient struct {
	conn mqc.Conn
}

func NewRpcTestClient(conn mqc.Conn) *rpcTestClient {
	return &rpcTestClient{conn: conn}
}

func (c *rpcTestClient) Rpc(ctx context.Context, req *TestRequest) (*TestReply, error) {
	return mqc.Rpc[TestRequest, TestReply](ctx, c.conn, mqc.Method("RpcTest/Rpc"), req)
}

type serverStreamTestClient struct {
	conn mqc.Conn
}

func NewServerStreamTestClient(conn mqc.Conn) *serverStreamTestClient {
	return &serverStreamTestClient{conn: conn}
}

func (c *serverStreamTestClient) Stream(ctx context.Context, req *TestRequest) (mqc.ServerStreamClient[TestReply], error) {
	return mqc.NewServerStreamClient[TestRequest, TestReply](ctx, c.conn, mqc.Method("ServerStreamTest/Stream"), req)
}

type clientStreamTestClient struct {
	conn mqc.Conn
}

func NewClientStreamTestClient(conn mqc.Conn) *clientStreamTestClient {
	return &clientStreamTestClient{conn: conn}
}

func (c *clientStreamTestClient) Stream(ctx context.Context) (mqc.ClientStreamClient[TestRequest, TestReply], error) {
	return mqc.NewClientStreamClient[TestRequest, TestReply](ctx, c.conn, mqc.Method("ClientStreamTest/Stream"))
}

type bidiStreamTestClient struct {
	conn mqc.Conn
}

func NewBidiStreamTestClient(conn mqc.Conn) *bidiStreamTestClient {
	return &bidiStreamTestClient{conn: conn}
}

func (c *bidiStreamTestClient) Stream(ctx context.Context) (mqc.BidiStreamClient[TestRequest, TestReply], error) {
	return mqc.NewBidiStreamClient[TestRequest, TestReply](ctx, c.conn, mqc.Method("BidiStreamTest/Stream"))
}

type UnimplementedRpcTestServer struct{}

func (s *UnimplementedRpcTestServer) Rpc(req *TestRequest) (*TestReply, error) {
	return nil, fmt.Errorf("method Rpc not implemented")
}

func RegisterRpcTestServer(conn mqc.Conn, server RpcTestServer) {
	conn.RegisterHandler("RpcTest/Rpc", func(call mqc.Call) error {
		return mqc.RpcServer(call, conn.Serializer(), func(req *TestRequest) (*TestReply, error) {
			return server.Rpc(req)
		})
	})
}

type UnimplementedServerStreamTestServer struct{}

func (s *UnimplementedServerStreamTestServer) Stream(req *TestRequest, stream mqc.ServerStreamServer[TestReply]) error {
	return fmt.Errorf("method Stream not implemented")
}

func RegisterServerStreamTestServer(conn mqc.Conn, server ServerStreamTestServer) {
	conn.RegisterHandler("ServerStreamTest/Stream", func(call mqc.Call) error {
		stream, req, err := mqc.NewServerStreamServer[TestRequest, TestReply](conn, call)
		if err != nil {
			return err
		}
		return server.Stream(req, stream)
	})
}

type UnimplementedClientStreamTestServer struct{}

func (s *UnimplementedClientStreamTestServer) Stream(stream mqc.ClientStreamServer[TestRequest, TestReply]) error {
	return fmt.Errorf("method Stream not implemented")
}

func RegisterClientStreamTestServer(conn mqc.Conn, server ClientStreamTestServer) {
	conn.RegisterHandler("ClientStreamTest/Stream", func(call mqc.Call) error {
		stream, err := mqc.NewClientStreamServer[TestRequest, TestReply](conn, call)
		if err != nil {
			return err
		}
		return server.Stream(stream)
	})
}

type UnimplementedBidiStreamTestServer struct{}

func (s *UnimplementedBidiStreamTestServer) Stream(stream mqc.BidiStreamServer[TestRequest, TestReply]) error {
	return fmt.Errorf("method Stream not implemented")
}

func RegisterBidiStreamTestServer(conn mqc.Conn, server BidiStreamTestServer) {
	conn.RegisterHandler("BidiStreamTest/Stream", func(call mqc.Call) error {
		stream, err := mqc.NewBidiStreamServer[TestRequest, TestReply](conn, call)
		if err != nil {
			return err
		}
		return server.Stream(stream)
	})
}
