// Code generated by protoc-gen-mqc. DO NOT EDIT.
// versions:
// protoc-gen-go-mqc v1.0.0

package loadbalancer

import (
	"context"
	"fmt"
	"github.com/srand/mqc"
)

type EntropyClient interface {
	GenerateIntegers(ctx context.Context, req *NumberRequest) (mqc.ServerStreamClient[NumberReply], error)
}

type EntropyServer interface {
	GenerateIntegers(req *NumberRequest, stream mqc.ServerStreamServer[NumberReply]) error
}

type entropyClient struct {
	conn mqc.Conn
}

func NewEntropyClient(conn mqc.Conn) *entropyClient {
	return &entropyClient{conn: conn}
}

func (c *entropyClient) GenerateIntegers(ctx context.Context, req *NumberRequest) (mqc.ServerStreamClient[NumberReply], error) {
	return mqc.NewServerStreamClient[NumberRequest, NumberReply](ctx, c.conn, mqc.Method("Entropy/GenerateIntegers"), req)
}

type UnimplementedEntropyServer struct{}

func (s *UnimplementedEntropyServer) GenerateIntegers(req *NumberRequest, stream mqc.ServerStreamServer[NumberReply]) error {
	return fmt.Errorf("method GenerateIntegers not implemented")
}

func RegisterEntropyServer(conn mqc.Conn, server EntropyServer) {
	conn.RegisterHandler("Entropy/GenerateIntegers", func(call mqc.Call) error {
		stream, req, err := mqc.NewServerStreamServer[NumberRequest, NumberReply](conn, call)
		if err != nil {
			return err
		}
		return server.GenerateIntegers(req, stream)
	})
}
