// Code generated by protoc-gen-mqc. DO NOT EDIT.
// versions:
// protoc-gen-go-mqc v1.0.0

package loadbalancer

import (
	"context"
	"fmt"
	"github.com/srand/mqc"
)

type EntropyClient interface {
	GenerateIntegers(ctx context.Context, req *NumberRequest) (mqc.ServerStreamClient[NumberReply], error)
}

type EntropyServer interface {
	GenerateIntegers(req *NumberRequest, stream mqc.ServerStreamServer[NumberReply]) error
}

type entropyClient struct {
	transport mqc.Transport
}

func NewEntropyClient(transport mqc.Transport) *entropyClient {
	return &entropyClient{transport: transport}
}

func (c *entropyClient) GenerateIntegers(ctx context.Context, req *NumberRequest) (mqc.ServerStreamClient[NumberReply], error) {
	return mqc.NewServerStreamClient[NumberRequest, NumberReply](ctx, c.transport, mqc.Method("Entropy/GenerateIntegers"), req)
}

type UnimplementedEntropyServer struct{}

func (s *UnimplementedEntropyServer) GenerateIntegers(req *NumberRequest, stream mqc.ServerStreamServer[NumberReply]) error {
	return fmt.Errorf("method GenerateIntegers not implemented")
}

func RegisterEntropyServer(transport mqc.Transport, server EntropyServer) {
	transport.RegisterHandler("Entropy/GenerateIntegers", func(conn mqc.Conn) error {
		stream, req, err := mqc.NewServerStreamServer[NumberRequest, NumberReply](transport, conn)
		if err != nil {
			return err
		}
		return server.GenerateIntegers(req, stream)
	})
}
