// Code generated by protoc-gen-mqc. DO NOT EDIT.
// versions:
// protoc-gen-go-mqc v1.0.0

package helloworld

import (
	"context"
	"fmt"
	"github.com/srand/mqc"
)

type GreeterClient interface {
	SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error)
}

type GreeterServer interface {
	SayHello(req *HelloRequest) (*HelloReply, error)
}

type greeterClient struct {
	transport mqc.Transport
}

func NewGreeterClient(transport mqc.Transport) *greeterClient {
	return &greeterClient{transport: transport}
}

func (c *greeterClient) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return mqc.Rpc[HelloRequest, HelloReply](ctx, c.transport, mqc.Method("Greeter/SayHello"), req)
}

type UnimplementedGreeterServer struct{}

func (s *UnimplementedGreeterServer) SayHello(req *HelloRequest) (*HelloReply, error) {
	return nil, fmt.Errorf("method SayHello not implemented")
}

func RegisterGreeterServer(transport mqc.Transport, server GreeterServer) {
	transport.RegisterHandler("Greeter/SayHello", func(conn mqc.Conn) error {
		return mqc.RpcServer(conn, transport.Serializer(), func(req *HelloRequest) (*HelloReply, error) {
			return server.SayHello(req)
		})
	})
}
