// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: bidi.proto

package websocket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Integer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integer) Reset() {
	*x = Integer{}
	mi := &file_bidi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integer) ProtoMessage() {}

func (x *Integer) ProtoReflect() protoreflect.Message {
	mi := &file_bidi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integer.ProtoReflect.Descriptor instead.
func (*Integer) Descriptor() ([]byte, []int) {
	return file_bidi_proto_rawDescGZIP(), []int{0}
}

func (x *Integer) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_bidi_proto protoreflect.FileDescriptor

const file_bidi_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bidi.proto\x12\twebsocket\"\x1f\n" +
	"\aInteger\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value2H\n" +
	"\vIncrementer\x129\n" +
	"\tIncrement\x12\x12.websocket.Integer\x1a\x12.websocket.Integer\"\x00(\x010\x01B\x14Z\x12examples/websocketb\x06proto3"

var (
	file_bidi_proto_rawDescOnce sync.Once
	file_bidi_proto_rawDescData []byte
)

func file_bidi_proto_rawDescGZIP() []byte {
	file_bidi_proto_rawDescOnce.Do(func() {
		file_bidi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bidi_proto_rawDesc), len(file_bidi_proto_rawDesc)))
	})
	return file_bidi_proto_rawDescData
}

var file_bidi_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bidi_proto_goTypes = []any{
	(*Integer)(nil), // 0: websocket.Integer
}
var file_bidi_proto_depIdxs = []int32{
	0, // 0: websocket.Incrementer.Increment:input_type -> websocket.Integer
	0, // 1: websocket.Incrementer.Increment:output_type -> websocket.Integer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bidi_proto_init() }
func file_bidi_proto_init() {
	if File_bidi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bidi_proto_rawDesc), len(file_bidi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidi_proto_goTypes,
		DependencyIndexes: file_bidi_proto_depIdxs,
		MessageInfos:      file_bidi_proto_msgTypes,
	}.Build()
	File_bidi_proto = out.File
	file_bidi_proto_goTypes = nil
	file_bidi_proto_depIdxs = nil
}
